# -*- coding: utf-8 -*-
"""Calculo-Medidas de Posicao-Preco Ponto de Funcao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14F5O418cC2u7wY-Pqmhc4Fy2Cp66Qbm5

## Cálculos de medidas de Posição acerca de preços unitários de pontos de função com objetivo similar ao contrato 014/2024/SEPLAG, para análise de dados.
"""

# Importda função para Cálculo da Moda
from statistics import mode

# Dados
dadosModa = [886.51, 886.51, 565.15, 550.00, 707.64]

# Calculando a moda
mode(dadosModa)

# Impor tda função para Cálculo da Median
from statistics import median

# Dados
dadosMediana = [886.51, 886.51, 565.15, 550.00, 707.64]

# Calculando a mediana
median(dadosMediana)

# Import da função para Cálculo da Média
from statistics import mean

# Dados
dadosMedia = [886.51, 886.51, 565.15, 550.00, 707.64]

# Calculando a média
mean(dadosMedia)